version: "3"
services:
  postgres-server:
    image: postgres:14.0
    container_name: postgres-server
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-d",
          "mydatabase",
          "-U",
          "myuser"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  data-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: data-generator
    env_file:
      - .env
    depends_on:
      postgres-server:
        condition: service_healthy
    command: [ "postgres-server" ]

networks:
  default:
    name: mlops-network
